mysite/mysite/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
	path('retrobaza/', include('retrobaza.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/retrobaza/urls.py
from django.urls import include, path, re_path
from django.conf.urls import url
from rest_framework import routers

from .views import (
  RBIndex, 
  RBContact, 
  RBPartners, 
  RBSignUp, 
  RBFCategories, 
  RBFTopics, 
  RBFTopic, 
  RBBMain, 
  RBBBrand, 
  RBBType, 
  RBBModel, 
  ModelCreatePopup, 
  BrandCreatePopup, 
  TypeCreatePopup, 
  EditUserData, 
  deleteFile, 
  deleteTopic, 
  EditProfile,
  DeleteUserConfirm,
  editFile,
  editTopic,
  AdminOptions,
  BrandManageView,
  ModelNameManageView,
  DeviceTypeManageView,
  PostManageView,
  TopicManageView,
  BrandList,
  ModelNameList,
  DeviceTypeList,
  PostList,
  TopicList,
  CategoryManageView,
  CategoryList,
  FileManageView,
  FileList
) 
from retrobaza import views

urlpatterns = [
  path('', RBIndex.as_view(), name='retrobaza-index'),
  path('contact/', RBContact.as_view(), name='retrobaza-contact'),
  path('partners/', RBPartners.as_view(), name='retrobaza-partners'),
  re_path(r'^register/$',views.RBSignUp, name='retrobaza-register'),
  re_path(r'^forum/$', views.RBFCategories, name='retrobaza-forum'),
  re_path(r'^forum/(?P<slug>[^/]+)/?$', views.RBFTopics, name='forum-topic'),
  re_path(r'^topic/(?P<slug>[^/]+)/?$', views.RBFTopic, name='topic-details'),
  re_path(r'^topic-add/', views.RBFNTopic, name='topic-new'),
  re_path(r'^topic-reply/(?P<pk>[^/]+)/?$', views.RBFNPost, name='post-new'),
  re_path(r'^library/$', views.RBBMain, name='retrobaza-library'),
  re_path(r'^library/(?P<slug>[^/]+)/?$', views.RBBBrand, name='library-brand'),
  re_path(r'^library/type/(?P<slug>[^/]+)/?$', views.RBBType, name='library-type'),
  re_path(r'^library/(?P<brandSlug>[^/]+)/(?P<modelSlug>[^/]+)/?$', views.RBBModel, name='library-model'),
  re_path(r'^library-add/', views.RBBAdd, name='file-new'),
  path('ajax/load-models/', views.load_models, name='ajax_load_models'),
  url(r'^brand/create', BrandCreatePopup, name = "BrandCreate"),
  url(r'^model/create', ModelCreatePopup, name = "ModelCreate"),
  url(r'^type/create', TypeCreatePopup, name = "TypeCreate"),
  re_path(r'^user/edit/?$', views.EditUserData, name='editUser'),
  path('user/file/<pk>/delete/', views.deleteFile, name='deleteFile'),
  path('user/topic/<pk>/delete/', views.deleteTopic, name='deleteTopic'),
  re_path(r'^user/edit/data/?$', views.EditProfile, name='editUserData'),
  re_path(r'^user/edit/password/?$', views.EditPassword, name='editUserPassword'),
  re_path(r'^user/delete_confirm/?$', views.DeleteUserConfirm, name='deleteAccountConfirm'),
  path('topic/<int:pk>/edit/', views.editTopic, name='editTopic'),
  path('file/<int:pk>/edit/', views.editFile, name='editFile'),
  re_path(r'^user/edit/avatar/?$', views.EditAvatar, name='editUserAvatar'),
  re_path(r'^admin/', views.AdminOptions, name='adminOptions'),
  path('lock-user/<pk>/', views.AdminLockUser, name='lockUser'),
  path('edit-type/<int:pk>/', views.AdminChangeStatus, name='editUserType'),
  url(r'^brand_api/(?P<pk>\d+)$', BrandManageView.as_view()),
  url(r'^brands_api/?$', BrandList.as_view()),   
  url(r'^model_api/(?P<pk>\d+)$', ModelNameManageView.as_view()),
  url(r'^models_api/?$', ModelNameList.as_view()),    
  url(r'^devicetype_api/(?P<pk>\d+)$', DeviceTypeManageView.as_view()),
  url(r'^devicetypes_api/?$', DeviceTypeList.as_view()),
  url(r'^post_api/(?P<pk>\d+)$', PostManageView.as_view()),
  url(r'^posts_api/?$', PostList.as_view()),
  url(r'^topic_api/(?P<pk>\d+)$', TopicManageView.as_view()),
  url(r'^topics_api/?$', TopicList.as_view()),    
  url(r'^category_api/(?P<pk>\d+)$', CategoryManageView.as_view()),
  url(r'^categories_api/?$', CategoryList.as_view()),
  url(r'^file_api/(?P<pk>\d+)$', FileManageView.as_view()),
  url(r'^files_api/?$', FileList.as_view()),
  path('ajax/topic/addpost/', views.NewPost),
  url(r'^topicentry/$', views.topicentry, name='topicentry'),
]

mysite/retrobaza/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver
from django.template.defaultfilters import slugify


#Model of user (needed - added avatar field)
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='user_avatars/', blank=True, null=True)
    is_blocked = models.BooleanField(default=False)
    @receiver(post_save, sender=User)
    def update_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
        instance.profile.save()
    def __str__(self):
        return self.user.username
    def delete(self, *args, **kwargs):
        self.avatar.delete()
        self.user.delete()
        super().delete(*args, **kwargs)

#Model of brand
class Brand(models.Model):
    brandName = models.CharField(max_length=50)
    brandSlug = models.SlugField()
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.brandSlug = slugify(self.brandName)

        super(Brand, self).save(*args, **kwargs)
    def __str__(self):
        return self.brandName

#Model of model name
class ModelName(models.Model):
    modelName = models.CharField(max_length=50)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    modelSlug = models.SlugField()
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.modelSlug = slugify(self.modelName)

        super(ModelName, self).save(*args, **kwargs)
    def __str__(self):
        return self.modelName

#Model of device Type
class DeviceType(models.Model):
    deviceTypeName = models.CharField(max_length=50)
    deviceSlug = models.SlugField()
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.deviceSlug = slugify(self.deviceTypeName)

        super(DeviceType, self).save(*args, **kwargs)
    def __str__(self):
        return self.deviceTypeName

### Model of file (Commented due to the unknown interpretation of file upload scheme)

def user_directory_path(instance, filename):
    return '{0}/{1}/{2}'.format(instance.model.brand.brandSlug, instance.model.modelSlug, filename)

class File(models.Model):
    fileName = models.CharField(max_length=200)
    fileDesc = models.TextField()
    uploader = models.ForeignKey(Profile,null=True, on_delete=models.SET_NULL)
    brand = models.ForeignKey(Brand, null=True, on_delete=models.SET_NULL)
    model = models.ForeignKey(ModelName,null=True, on_delete=models.SET_NULL)
    deviceType = models.ForeignKey(DeviceType,null=True, on_delete=models.SET_NULL)
    file = models.FileField(upload_to=user_directory_path )
    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


#Model of forum category
class Category(models.Model):
    catName = models.CharField(max_length=50)
    catDesc = models.CharField(max_length=255)
    catPic = models.ImageField(upload_to='forum_cats')
    catSlug =  models.SlugField()
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.catSlug = slugify(self.catName)

        super(Category, self).save(*args, **kwargs)
    def __str__(self):
        return self.catName

#Model of forum topic
class Topic(models.Model):
    author = models.ForeignKey(Profile,null=True, on_delete=models.SET_NULL)
    titleCat = models.ForeignKey(Category, on_delete=models.CASCADE)
    titleName = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    titleSlug =  models.SlugField()
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.titleSlug = slugify(self.titleName)

        super(Topic, self).save(*args, **kwargs)
    def __str__(self):
        return self.titleName

#Model of forum post
class Post(models.Model):
    author = models.ForeignKey(Profile,null=True, on_delete=models.SET_NULL)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    postData = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

mysite/retrobaza/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import Brand, ModelName, DeviceType, Category, Topic, Post, File, Profile

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Pole opcjonalne')
    last_name = forms.CharField(max_length=30, required=False, help_text='Pole opcjonalne')
    email = forms.EmailField(max_length=254, help_text='Pole wymagane')
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class AddTopic(forms.ModelForm):
    titleCat = forms.ModelChoiceField(queryset=Category.objects.all(),to_field_name='catName')
    class Meta:
        model = Topic
        fields = ('titleName', 'titleCat',)

class AddPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('postData',)

class AddFile(forms.ModelForm):
    class Meta:
        model = File
        fields = ('fileName', 'fileDesc', 'brand', 'model', 'deviceType', 'file', )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['model'].queryset = ModelName.objects.none()
        if 'brand' in self.data:
                try:
                    brand = int(self.data.get('brand'))
                    self.fields['model'].queryset = ModelName.objects.filter(brand = brand).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['model'].queryset = self.instance.brand.modelname_set.order_by('modelName')

class AddModel(forms.ModelForm):
    class Meta:
        model = ModelName
        fields = ('modelName', 'brand',)

class AddBrand(forms.ModelForm):
    class Meta:
        model = Brand
        fields = ('brandName',)

class AddType(forms.ModelForm):
    class Meta:
        model = DeviceType
        fields = ('deviceTypeName',)

class EditUserForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password'
        )

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'avatar',
        )

class DeleteConfirm(forms.Form):
    userId = forms.IntegerField(widget=forms.HiddenInput())

class ChangeUserType(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'is_staff',
            'is_superuser',
            'password'
        )

mysite/retrobaza/templates/addPost.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-10">
        <form method="post">
            {% csrf_token %}
                {% for pfield in add_post %}
                    <div>
                        {{ pfield.label_tag }}<br>
                        {{ pfield }}
                        {% for error in pfield.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
         <button class="btn btn-secondary" type="submit">Dodaj odpowiedź</button>
        </form>
    </div>
</div>
{% endblock %}

mysite/retrobaza/templates/addTopic.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-10">
        <form method="post">
            {% csrf_token %}
                {% for field in add_topic %}
                    <div>
                        {{ field.label_tag }}<br>
                        {{ field }}
                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
                {% for pfield in add_post %}
                    <div>
                        {{ pfield.label_tag }}<br>
                        {{ pfield }}
                        {% for error in pfield.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
         <button class="btn btn-secondary" type="submit">Dodaj temat</button>
        </form>
    </div>
</div>
{% endblock %}

mysite/retrobaza/templates/adminChangeType.html
{% extends 'base.html' %}

{% block content %}
    <div class="main">
        <div class="row">
            <h2>Zmień rodzaj użytkownika:</h2>
        </div>
        <div class="col-md-10">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Zmień ustawienia</button>
                <a href="{% url 'adminOptions' %}">Anuluj</a>
            </form>
        </div>
    </div>
{% endblock %}

mysite/retrobaza/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>RetroBaza.pl</title>
<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css?family=Merriweather|VT323" rel="stylesheet">
<link rel="stylesheet" href="{% static 'styles/basestyle.css' %}">
<link rel="stylesheet" href="{% static 'styles/cropper.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.0.min.js" integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'scripts/cropper.js' %}"></script>
<script type="text/javascript" src="{% static 'scripts/jquery-cropper.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
<div class="pageHeader">
    <div class="title">
        <h1><a href="{% url 'retrobaza-index' %}">RetroBaza-Nowe miejsce dla starych maszyn</a></h1>
    </div>
        <nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color ">
        <a class="navbar-brand" href="{% url 'retrobaza-index' %}">RetroBaza</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
        aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'retrobaza-library' %}">Biblioteka</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'retrobaza-contact' %}">Kontakt</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'retrobaza-partners' %}">Partnerzy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'retrobaza-forum' %}">Forum</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <form class="form-inline my-1">
                <div class="md-form form-sm my-0">
                    <input class="form-control form-control-sm mr-sm-2 mb-0" type="text" placeholder="Search" aria-label="Search">
                </div>
                <button class="btn btn-outline-white btn-sm my-0" type="submit">Szukaj</button>
            </form>
            {% endif %}
            <ul class="navbar-nav ml-auto nav-flex-icons">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    Witaj<b>
                    {% if user.is_authenticated %} {{ user.get_username }}
                    {% else %}niezalogowany
                    {% endif %}</b>
                    </a>
                <div class="dropdown-menu dropdown-menu-right dropdown-default" aria-labelledby="navbarDropdownMenuLink-333">
                {% if user.is_authenticated %}
                    {% if user.is_staff or user.is_superuser %}
                        <a class="dropdown-item" href="{% url 'adminOptions' %}">Ustawienia zaawansowane</a>
                    {% endif %}
                    <a class="dropdown-item" href="{% url 'editUser' %}">Zmień ustawienia</a>
                    <a class="dropdown-item" href="{% url 'logout' %}">Wyloguj się</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'login' %}">Zaloguj się</a>
                    <a class="dropdown-item" href="{% url 'retrobaza-register' %}">Zarejestruj się</a>
                {% endif %}
                </div>
                </li>
            </ul>
        </div>
    </nav>
</div>
<div class="pageBody">
{% block content %}
{% endblock %}
</div>
<div class="pageFooter">
Copyright 2019 Krzysztof Piskorz. Powered with Django.
</div>
</body>
</html>

mysite/retrobaza/templates/base_form.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>RetroBaza.pl - dodaj dane</title>
<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css?family=Merriweather|VT323" rel="stylesheet">
<link rel="stylesheet" href="{% static 'styles/basestyle.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.4.0.min.js" integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
<div class="pageHeader">
    <div class="title">
        <h1>RetroBaza-Nowe miejsce dla starych maszyn</h1>
    </div>
<div class="pageBody">
{% block content %}
{% endblock %}
</div>
<div class="pageFooter">
Copyright 2019 Krzysztof Piskorz. Powered with Django.
</div>
</body>
</html>

mysite/retrobaza/templates/deleteConfirm.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
    <div class="row"><h2> Czy na pewno chcesz usunąć konto. Ta operacja jest nieodwracalna.</h2></div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Usuń konto</button>
            <a href="{% url 'editUser' %}">Anuluj</a>
        </form>
    </div>
{% endblock %}

mysite/retrobaza/templates/editAvatar.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
  <h2>Zmień awatar:</h2>
  </div>
  <div class="col-md-10">
  <form method="post" enctype="multipart/form-data" id="registerform">
    {% csrf_token %}
     <div>
     {{photoform}}
     </div>
    <button type="submit">Zmiana avatara</button>
  </form>
  </div>
</div>

<div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Przytnij zdjęcie</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Anuluj</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Przytnij</button>
        </div>
      </div>
    </div>
  </div>

<script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#registerform").submit();
      });

    });
  </script>

{% endblock %}

mysite/retrobaza/templates/editUserData.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Zmień ustawienia</button>
            <a href="{% url 'editUser' %}">Anuluj</a>
        </form>
    </div>
{% endblock %}

mysite/retrobaza/templates/libraryAddFile.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
    <div class="col-md-10">
        <form method="post" id="fileform" data-models-url="{% url 'ajax_load_models' %}" enctype="multipart/form-data">
            {% csrf_token %}
                <div>
                        <label for="id_fileName">Nazwa pliku:</label><br>
                        {{add_file.fileName}}
                    </div>
                
                    <div>
                        <label for="id_fileDesc">Opis pliku:</label><br>
                        {{add_file.fileDesc}}
                    </div>
                
                    <div>
                        <label for="id_brand">Marka:</label><br>
						{{add_file.brand}}
                        <a href="{% url 'BrandCreate' %}" id="add_brand" onclick="return showAddPopup(this);">+</a>
                    </div>
                
                    <div>
                        <label for="id_model">Model:</label><br>
						{{add_file.model}}
						<a href="{% url 'ModelCreate' %}" id="add_model" onclick="return showAddPopup(this);">+</a>
                    </div>
                
                    <div>
                        <label for="id_deviceType">Typ urządzenia:</label><br>
						{{add_file.deviceType}}
						<a href="{% url 'TypeCreate' %}" id="add_type" onclick="return showAddPopup(this);">+</a>
                    </div>
                
                    <div>
                        <label for="id_file">Plik:</label><br>
                        {{add_file.file}}
                    </div>
         <button class="btn btn-secondary" type="submit">Dodaj plik</button>
        </form>
    </div>
</div>
<script>
    $("#id_brand").change(function () {
      var url = $("#fileform").attr("data-models-url");  // get the url of the `load_cities` view
      var brandID = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'brand': brandID       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_model").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
    function showAddPopup(triggeringLink) {
    var brand = triggeringLink.id.replace(/^add_/, '');
    href = triggeringLink.href;
    var win = window.open(href, brand, 'height=500,width=800,resizable=yes,scrollbars=yes');
    win.focus();
    return false;
}
    function closePopup(win, newID, newRepr, id) {
    $(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
    win.close();
}
  </script>
{% endblock %}

mysite/retrobaza/templates/partners.html
{% extends 'base.html' %}

{% block content %}
    <div class="main">
    <h1> Partnerzy RetroBazy: </h1>
    </div>
{% endblock %}